### ISSUE TITLE
[doubt] want clarification on something

### ISSUE THREAD

**Issue by MNkoder** [sudoharun/sudoharun#1]
hey just wanted to ask you if you're still using kde coz i just saw a new commit in your Hyprland repo 2 days back, btw sorry for making this issue on your profile lol 😭

**Comment by sudoharun** [comment]
Hi, I very recently switched back to Arch + Hyprland and I still have not updated my profile.

**Comment by MNkoder** [comment]
yeah jsut saw that your profile was updated now and was confused when i saw kde

**Comment by MNkoder** [comment]
Also do you happen to use ags now instead of eww? if i wanted to try your new ags dots, will i be good to go by following the guide on the modernish branch (it still says to clone the retroesque branch in the readme) and just clone the modernish branch instead of the retroesque branch? ik its so random really sorry btw

**Comment by sudoharun** [comment]
My AGS dotfiles are not ready yet hence they are not mentioned on the main branch nor is the README in the modernish branch updated. I still am currently using them however, and if you also want to use it you can copy all the files from the config folder into `$HOME/.config`. Any issues please make an issue ![here](https://github.com/sudoharun/dotfiles/issues).
